"""empty message

Revision ID: c1f622068c55
Revises: 
Create Date: 2020-05-12 20:42:18.646145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f622068c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_users')
    op.add_column('blog_post', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('blog_post', 'blog_post')
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.add_column('blog_post', sa.Column('blog_post', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blog_post', 'body')
    op.create_table('blog_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_users_pkey')
    )
    # ### end Alembic commands ###
